# Generated by Django 4.1.5 on 2023-02-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
                ('st_district', models.CharField(max_length=50)),
                ('st_lat', models.FloatField()),
                ('st_lng', models.FloatField()),
                ('st_river', models.CharField(max_length=50)),
                ('st_waterlevel_measured', models.FloatField()),
                ('st_warning_level', models.FloatField()),
                ('st_Danger_level', models.FloatField()),
            ],
        ),
    ]
