# Generated by Django 4.1.5 on 2023-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('evacuationNo', models.IntegerField()),
            ],
        ),
    ]
