# Generated by Django 4.1.5 on 2023-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_evacuationmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationmsg',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
